name: Unittests

on:
  pull_request:
    branches: [ main-stage ]
  push:
    branches: [ main-stage ]

jobs:
  unittests:
    name: unittests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: |
        env | sort
        make all ENVS=linux-amd64

    - name: Verify
      run: |
        make verify

    - name: Test
      run: |
        make test ENVS=linux-amd64

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage1.txt,./coverage2.txt,./coverage3.txt,./cli/core/coverage.txt,./cli/runtime/coverage.txt,./cmd/cli/plugin-admin/builder/cover.out,./cmd/cli/plugin-admin/codegen/cover.out,./cmd/cli/plugin-admin/test/cover.out,./cmd/cli/plugin/login/cover.out
  check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache linting
      uses: actions/cache@v3
      with:
        path: ${{ runner.temp }}/lint_cache
        key: ${{ runner.os }}-lint-cache

    - name: Run lint checks
      env:
        GOLANGCI_LINT_CACHE: ${{ runner.temp }}/lint_cache
      run: |
        make lint
